
/* Home */
export const SET_HOME_SUMMARY = "SET_HOME_SUMMARY";


/* Profile */
export const DISPLAY_MANAGER_PICTURE_MODAL = "DISPLAY_MANAGER_PICTURE_MODAL";
export const DISMISS_MANAGER_PICTURE_MODAL = "DISMISS_MANAGER_PICTURE_MODAL";

export const DISPLAY_CENTER_PICTURE_MODAL = "DISPLAY_CENTER_PICTURE_MODAL";
export const DISMISS_CENTER_PICTURE_MODAL = "DISMISS_CENTER_PICTURE_MODAL";

export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PHONE = "SET_PHONE";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_NAME = "SET_NAME";
export const SET_SIRET = "SET_SIRET";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ADDRESS_SECOND = "SET_ADDRESS_SECOND";
export const SET_ZIP_CODE = "SET_ZIP_CODE";
export const SET_CITY = "SET_CITY";
export const SET_CENTER_PHONE = "SET_CENTER_PHONE";
export const SET_REMEMBER = "SET_REMEMBER";

export const RESET_REGISTER_INFO = "RESET_REGISTER_INFO";
export const RESET_PROFILE_INFO = "RESET_PROFILE_INFO";

export const RESET_MANAGER_CENTER_INFO = "RESET_MANAGER_CENTER_INFO";

export const SET_MANAGER_KEEP_INFO = "SET_MANAGER_KEEP_INFO";
export const SET_CENTER_KEEP_INFO = "SET_CENTER_KEEP_INFO";

export const SET_MANAGER_INFO = "SET_MANAGER_INFO";
export const SET_CENTER_INFO = "SET_CENTER_INFO";

export const SET_MANAGER_PICTURE_PREVIEW = "SET_MANAGER_PICTURE_PREVIEW";
export const SET_CENTER_PICTURE_PREVIEW = "SET_CENTER_PICTURE_PREVIEW";

export const SET_MANAGER_PICTURE = "SET_MANAGER_PICTURE";
export const SET_CENTER_PICTURE = "SET_CENTER_PICTURE";

/* ProfileSocial */
export const SET_PUBLICATIONS = "SET_PUBLICATIONS";
export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const SET_CURRENT_PUBLICATION = "SET_CURRENT_PUBLICATION";
export const DISPLAY_PUBLICATION_DELETE_CONFIRM = "DISPLAY_PUBLICATION_DELETE_CONFIRM";
export const DISMISS_PUBLICATION_DELETE_CONFIRM = "DISMISS_PUBLICATION_DELETE_CONFIRM";


/* ProfilePhotos */
export const DISPLAY_PHOTO_MODAL = "DISPLAY_PHOTO_MODAL";
export const DISMISS_PHOTO_MODAL = "DISMISS_PHOTO_MODAL";
export const SET_PHOTOS = "SET_PHOTOS";
export const ADD_PHOTO = "ADD_PHOTO";
export const DELETE_PHOTO = "DELETE_PHOTO";
export const SET_PICTURE_TITLE = "SET_PICTURE_TITLE";
export const SET_PICTURE_DESCRIPTION = "SET_PICTURE_DESCRIPTION";
export const SET_PICTURE_PREVIEW = "SET_PICTURE_PREVIEW";
export const DISPLAY_DELETE_PICTURE_CONFIRM = "DISPLAY_DELETE_PICTURE_CONFIRM";
export const DISMISS_DELETE_PICTURE_CONFIRM = "DISMISS_DELETE_PICTURE_CONFIRM";


/* Display */

export const SET_DISPLAY_CONFIGURATION = "SET_DISPLAY_CONFIGURATION";
export const SET_UPDATE_KEEP_DISPLAY_CONFIGURATION = "SET_UPDATE_KEEP_DISPLAY_CONFIGURATION";
export const SET_SHOW_EVENTS = "SET_SHOW_EVENTS";
export const SET_KEEP_EVENTS = "SET_KEEP_EVENTS";
export const SET_SELECTED_EVENTS = "SET_SELECTED_EVENTS";
export const SET_SHOW_NEWS = "SET_SHOW_NEWS";
export const SET_NEWS_TYPE = "SET_NEWS_TYPE";
export const SET_SHOW_GLOBAL_PERFORMANCES = "SET_SHOW_GLOBAL_PERFORMANCES";
export const SET_PERFORMANCES_TYPE = "SET_PERFORMANCES_TYPE";
export const SET_SHOW_RANKING_DISCIPLINE = "SET_SHOW_RANKING_DISCIPLINE";
export const SET_RANKING_DISCIPLINE_TYPE = "SET_RANKING_DISCIPLINE_TYPE";
export const SET_SHOW_GLOBAL_RANKING = "SET_SHOW_GLOBAL_RANKING";
export const SET_NATIONAL_PRODUCTION_RANK = "SET_NATIONAL_PRODUCTION_RANK";


/* Equipment */
export const SET_MODULES = "SET_MODULES";
export const SET_MODULE_STATES = "SET_MODULE_STATES";

/* Statistics */
export const SET_STATISTICS = "SET_STATISTICS";


/* Contact */
export const SET_FEEDBACKS = "SET_FEEDBACKS";
export const SET_INITIAL_FEEDBACKS = "SET_INITIAL_FEEDBACKS";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const SET_STATUS = "SET_STATUS";
export const SET_FILTER_KEYWORDS = "SET_FILTER_KEYWORDS";
export const SET_FILTER_STATUS = "SET_FILTER_STATUS";
export const SET_FEEDBACK_TITLE = "SET_FEEDBACK_TITLE";
export const SET_FEEDBACK_DESCRIPTION = "SET_FEEDBACK_DESCRIPTION";
export const DISPLAY_FEEDBACK_MODAL = "DISPLAY_FEEDBACK_MODAL";
export const DISMISS_FEEDBACK_MODAL = "DISMISS_FEEDBACK_MODAL";
export const DISPLAY_FEEDBACK_EDIT_MODAL = "DISPLAY_FEEDBACK_EDIT_MODAL";

/* Events */
export const SET_EVENTS = "SET_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const SET_INITIAL_EVENTS = "SET_INITIAL_EVENTS";
export const SET_FILTER_EVENTS_KEYWORDS = "SET_FILTER_EVENTS_KEYWORDS";
export const SET_FILTER_EVENTS_START_DATE = "SET_FILTER_EVENTS_START_DATE";
export const SET_FILTER_EVENTS_END_DATE = "SET_FILTER_EVENTS_END_DATE";
export const SET_FILTER_EVENTS_STATUS = "SET_FILTER_EVENTS_STATUS";
export const SET_FILTER_EVENTS_SUBSCRIBERS_SELECT = "SET_FILTER_EVENTS_SUBSCRIBERS_SELECT";
export const SET_FILTER_EVENTS_NUMBER_SUBSCRIBERS = "SET_FILTER_EVENTS_NUMBER_SUBSCRIBERS";
export const SET_DELETION_CAUSE = "SET_DELETION_CAUSE";
export const RESET_FILTERS = "RESET_FILTERS";
export const DISPLAY_DELETE_CONFIRM = "DISPLAY_DELETE_CONFIRM";
export const DISMISS_DELETE_CONFIRM = "DISMISS_DELETE_CONFIRM";
export const DISPLAY_EVENT_MODAL = "DISPLAY_EVENT_MODAL";
export const DISPLAY_EVENT_EDIT_MODAL = "DISPLAY_EVENT_EDIT_MODAL";
export const DISMISS_EVENT_MODAL = "DISMISS_EVENT_MODAL";
export const SET_EVENT_MODAL_CURRENT_TITLE = "SET_EVENT_MODAL_CURRENT_TITLE";
export const SET_EVENT_MODAL_CURRENT_DESCRIPTION = "SET_EVENT_MODAL_CURRENT_DESCRIPTION";
export const SET_EVENT_MODAL_CURRENT_START_DATE = "SET_EVENT_MODAL_CURRENT_START_DATE";
export const SET_EVENT_MODAL_CURRENT_END_DATE = "SET_EVENT_MODAL_CURRENT_END_DATE";
export const SET_EVENT_MODAL_CURRENT_PICTURE = "SET_EVENT_MODAL_CURRENT_PICTURE";
export const SET_EVENT_LAST_POST = "SET_EVENT_LAST_POST";

/* Custom Programs */
export const SET_ACTIVITIES = "SET_ACTIVITIES";
export const SET_CUSTOM_PROGRAMS = "SET_CUSTOM_PROGRAMS";
export const SET_INITIAL_CUSTOM_PROGRAMS = "SET_INITIAL_CUSTOM_PROGRAMS";
export const ADD_CUSTOM_PROGRAM = "ADD_CUSTOM_PROGRAM";
export const DELETE_CUSTOM_PROGRAM = "DELETE_CUSTOM_PROGRAM";
export const UPDATE_CUSTOM_PROGRAM = "UPDATE_CUSTOM_PROGRAM";
export const UPDATE_CUSTOM_PROGRAM_AVAILABILITY = "UPDATE_CUSTOM_PROGRAM_AVAILABILITY";
export const SET_CUSTOM_PROGRAMS_AVAILABILITIES = "SET_CUSTOM_PROGRAMS_AVAILABILITIES";
export const RESET_CUSTOM_PROGRAMS_AVAILABILITIES = "RESET_CUSTOM_PROGRAMS_AVAILABILITIES";
export const DISPLAY_CUSTOM_PROGRAM_MODAL = "DISPLAY_CUSTOM_PROGRAM_MODAL";
export const DISMISS_CUSTOM_PROGRAM_MODAL = "DISMISS_CUSTOM_PROGRAM_MODAL";
export const DISPLAY_CUSTOM_PROGRAM_EDIT_MODAL = "DISPLAY_CUSTOM_PROGRAM_EDIT_MODAL";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_NAME = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_NAME";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_PICTURE = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_PICTURE";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_NB_ACTIVITIES = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_NB_ACTIVITIES";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_TOTAL_TIME = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_TOTAL_TIME";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_ACTIVITIES = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_ACTIVITIES";
export const ADD_TO_CUSTOME_PROGRAMME_MODAL_CURRENT_ACTIVITIES = "ADD_TO_CUSTOME_PROGRAMME_MODAL_CURRENT_ACTIVITIES";
export const DELETE_TO_CUSTOME_PROGRAMME_MODAL_CURRENT_ACTIVITIES = "DELETE_TO_CUSTOME_PROGRAMME_MODAL_CURRENT_ACTIVITIES";
export const SET_CUSTOM_PROGRAM_MODAL_CURRENT_AVAILABLE = "SET_CUSTOM_PROGRAM_MODAL_CURRENT_AVAILABLE";

export const SET_FILTER_CUSTOM_PROGRAM_KEYWORDS = "SET_FILTER_CUSTOM_PROGRAM_KEYWORDS";
export const SET_FILTER_CUSTOM_PROGRAM_NUMBER_ACTIVITIES = "SET_FILTER_CUSTOM_PROGRAM_NUMBER_ACTIVITIES";
export const SET_FILTER_CUSTOM_PROGRAM_TOTAL_DURATION = "SET_FILTER_CUSTOM_PROGRAM_TOTAL_DURATION";
export const SET_FILTER_CUSTOM_PROGRAM_AVAILABLE = "SET_FILTER_CUSTOM_PROGRAM_AVAILABLE";
export const SET_FILTER_CUSTOM_PROGRAM_UNAVAILABLE = "SET_FILTER_CUSTOM_PROGRAM_UNAVAILABLE";
export const RESET_FILTER_CUSTOM_PROGRAM = "RESET_FILTER_CUSTOM_PROGRAM";

/* Global */
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

export const SET_DISPLAY_CONFIGURATION_IS_LOAD = "SET_DISPLAY_CONFIGURATION_IS_LOAD";
export const SET_STATISTICS_IS_LOAD = "SET_STATISTICS_IS_LOAD";
export const SET_HOME_SUMMARY_IS_LOAD = "SET_HOME_SUMMARY_IS_LOAD";
export const SET_CUSTOM_PROGRAMS_ACTIVITIES_IS_LOAD = "SET_CUSTOM_PROGRAMS_ACTIVITIES_IS_LOAD";
export const SET_CUSTOM_PROGRAMS_IS_LOAD = "SET_CUSTOM_PROGRAMS_IS_LOAD";
export const SET_MODULES_IS_LOAD = "SET_MODULES_IS_LOAD";
export const SET_MODULE_STATES_IS_LOAD = "SET_MODULE_STATES_IS_LOAD";
export const SET_FEEDBACKS_IS_LOAD = "SET_FEEDBACKS_IS_LOAD";
export const SET_FEEDBACKS_STATUS_IS_LOAD = "SET_FEEDBACKS_STATUS_IS_LOAD";
export const SET_EVENTS_IS_LOAD = "SET_EVENTS_IS_LOAD";
export const SET_MANAGER_PROFILE_IS_LOAD = "SET_MANAGER_PROFILE_IS_LOAD";
export const SET_CENTER_PROFILE_IS_LOAD = "SET_CENTER_PROFILE_IS_LOAD";
export const SET_CENTER_PICTURE_IS_LOAD = "SET_CENTER_PICTURE_IS_LOAD";
export const SET_MANAGER_PICTURE_IS_LOAD = "SET_MANAGER_PICTURE_IS_LOAD";
export const SET_PUBLICATIONS_IS_LOAD = "SET_PUBLICATIONS_IS_LOAD";
export const SET_ALBUM_IS_LOAD = "SET_ALBUM_IS_LOAD";

export const SET_DISPLAY_CONFIGURATION_IS_NOT_LOAD = "SET_DISPLAY_CONFIGURATION_IS_NOT_LOAD";
export const SET_STATISTICS_IS_NOT_LOAD = "SET_STATISTICS_IS_NOT_LOAD";
export const SET_HOME_SUMMARY_IS_NOT_LOAD = "SET_HOME_SUMMARY_IS_NOT_LOAD";
export const SET_CUSTOM_PROGRAMS_ACTIVITIES_IS_NOT_LOAD = "SET_CUSTOM_PROGRAMS_ACTIVITIES_IS_NOT_LOAD";
export const SET_CUSTOM_PROGRAMS_IS_NOT_LOAD = "SET_CUSTOM_PROGRAMS_IS_NOT_LOAD";
export const SET_MODULES_IS_NOT_LOAD = "SET_MODULES_IS_NOT_LOAD";
export const SET_MODULE_STATES_IS_NOT_LOAD = "SET_MODULE_STATES_IS_NOT_LOAD";
export const SET_FEEDBACKS_IS_NOT_LOAD = "SET_FEEDBACKS_IS_NOT_LOAD";
export const SET_FEEDBACKS_STATUS_IS_NOT_LOAD = "SET_FEEDBACKS_STATUS_IS_NOT_LOAD";
export const SET_EVENTS_IS_NOT_LOAD = "SET_EVENTS_IS_NOT_LOAD";
export const SET_MANAGER_PROFILE_IS_NOT_LOAD = "SET_MANAGER_PROFILE_IS_NOT_LOAD";
export const SET_CENTER_PROFILE_IS_NOT_LOAD = "SET_CENTER_PROFILE_IS_NOT_LOAD";
export const SET_CENTER_PICTURE_IS_NOT_LOAD = "SET_CENTER_PICTURE_IS_NOT_LOAD";
export const SET_MANAGER_PICTURE_IS_NOT_LOAD = "SET_MANAGER_PICTURE_IS_NOT_LOAD";
export const SET_PUBLICATIONS_IS_NOT_LOAD = "SET_PUBLICATIONS_IS_NOT_LOAD";
export const SET_ALBUM_IS_NOT_LOAD = "SET_ALBUM_IS_NOT_LOAD";