export const DISPLAY_ALERT = "SHOW_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

/* Profile */
export const DISPLAY_MANAGER_PICTURE_MODAL = "DISPLAY_MANAGER_PICTURE_MODAL";
export const DISMISS_MANAGER_PICTURE_MODAL = "DISMISS_MANAGER_PICTURE_MODAL";

export const DISPLAY_CENTER_PICTURE_MODAL = "DISPLAY_CENTER_PICTURE_MODAL";
export const DISMISS_CENTER_PICTURE_MODAL = "DISMISS_CENTER_PICTURE_MODAL";

export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PHONE = "SET_PHONE";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_NAME = "SET_NAME";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ADDRESS_SECOND = "SET_ADDRESS_SECOND";
export const SET_ZIP_CODE = "SET_ZIP_CODE";
export const SET_CITY = "SET_CITY";
export const SET_CENTER_PHONE = "SET_CENTER_PHONE";
export const SET_REMEMBER = "SET_REMEMBER";

export const RESET_REGISTER_INFO = "RESET_REGISTER_INFO";
export const RESET_PROFILE_INFO = "RESET_PROFILE_INFO";

export const RESET_MANAGER_CENTER_INFO = "RESET_MANAGER_CENTER_INFO";

export const SET_MANAGER_KEEP_INFO = "SET_MANAGER_KEEP_INFO";
export const SET_CENTER_KEEP_INFO = "SET_CENTER_KEEP_INFO";

export const SET_MANAGER_INFO = "SET_MANAGER_INFO";
export const SET_CENTER_INFO = "SET_CENTER_INFO";

export const SET_MANAGER_PICTURE_PREVIEW = "SET_MANAGER_PICTURE_PREVIEW";
export const SET_CENTER_PICTURE_PREVIEW = "SET_CENTER_PICTURE_PREVIEW";

export const SET_MANAGER_PICTURE = "SET_MANAGER_PICTURE";
export const SET_CENTER_PICTURE = "SET_CENTER_PICTURE";

export const SET_PUBLICATIONS = "SET_PUBLICATIONS";
export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const SET_CURRENT_PUBLICATION = "SET_CURRENT_PUBLICATION";

/* ProfilePhotos */
export const DISPLAY_PHOTO_MODAL = "DISPLAY_PHOTO_MODAL";
export const DISMISS_PHOTO_MODAL = "DISMISS_PHOTO_MODAL";
export const SET_PHOTOS = "SET_PHOTOS";
export const ADD_PHOTO = "ADD_PHOTO";
export const SET_PICTURE_TITLE = "SET_PICTURE_TITLE";
export const SET_PICTURE_DESCRIPTION = "SET_PICTURE_DESCRIPTION";
export const SET_PICTURE_PREVIEW = "SET_PICTURE_PREVIEW";

/* Contact */
export const SET_FEEDBACKS = "SET_FEEDBACKS";
export const SET_INITIAL_FEEDBACKS = "SET_INITIAL_FEEDBACKS";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const SET_STATUS = "SET_STATUS";
export const SET_FILTER_KEYWORDS = "SET_FILTER_KEYWORDS";
export const SET_FILTER_STATUS = "SET_FILTER_STATUS";
export const SET_FEEDBACK_TITLE = "SET_FEEDBACK_TITLE";
export const SET_FEEDBACK_DESCRIPTION = "SET_FEEDBACK_DESCRIPTION";
export const DISPLAY_FEEDBACK_MODAL = "DISPLAY_FEEDBACK_MODAL";
export const DISMISS_FEEDBACK_MODAL = "DISMISS_FEEDBACK_MODAL";
export const DISPLAY_FEEDBACK_EDIT_MODAL = "DISPLAY_FEEDBACK_EDIT_MODAL";

/* Events */
export const SET_EVENTS = "SET_EVENTS";
export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const SET_INITIAL_EVENTS = "SET_INITIAL_EVENTS";
export const SET_FILTER_EVENTS_KEYWORDS = "SET_FILTER_EVENTS_KEYWORDS";
export const SET_FILTER_EVENTS_START_DATE = "SET_FILTER_EVENTS_START_DATE";
export const SET_FILTER_EVENTS_END_DATE = "SET_FILTER_EVENTS_END_DATE";
export const SET_FILTER_EVENTS_STATUS = "SET_FILTER_EVENTS_STATUS";
export const SET_FILTER_EVENTS_SUBSCRIBERS_SELECT = "SET_FILTER_EVENTS_SUBSCRIBERS_SELECT";
export const SET_FILTER_EVENTS_NUMBER_SUBSCRIBERS = "SET_FILTER_EVENTS_NUMBER_SUBSCRIBERS";
export const RESET_FILTERS = "RESET_FILTERS";
export const DISPLAY_EVENT_MODAL = "DISPLAY_EVENT_MODAL";
export const DISPLAY_EVENT_EDIT_MODAL = "DISPLAY_EVENT_EDIT_MODAL";
export const DISMISS_EVENT_MODAL = "DISMISS_EVENT_MODAL";
export const SET_EVENT_MODAL_CURRENT_TITLE = "SET_EVENT_MODAL_CURRENT_TITLE";
export const SET_EVENT_MODAL_CURRENT_DESCRIPTION = "SET_EVENT_MODAL_CURRENT_DESCRIPTION";
export const SET_EVENT_MODAL_CURRENT_START_DATE = "SET_EVENT_MODAL_CURRENT_START_DATE";
export const SET_EVENT_MODAL_CURRENT_END_DATE = "SET_EVENT_MODAL_CURRENT_END_DATE";
export const SET_EVENT_MODAL_CURRENT_PICTURE = "SET_EVENT_MODAL_CURRENT_PICTURE";

/* Global */
export const SET_FEEDBACKS_IS_LOAD = "SET_FEEDBACKS_IS_LOAD";
export const SET_FEEDBACKS_STATUS_IS_LOAD = "SET_FEEDBACKS_STATUS_IS_LOAD";
export const SET_EVENTS_IS_LOAD = "SET_EVENTS_IS_LOAD";
export const SET_MANAGER_PROFILE_IS_LOAD = "SET_MANAGER_PROFILE_IS_LOAD";
export const SET_CENTER_PROFILE_IS_LOAD = "SET_CENTER_PROFILE_IS_LOAD";
export const SET_CENTER_PICTURE_IS_LOAD = "SET_CENTER_PICTURE_IS_LOAD";
export const SET_MANAGER_PICTURE_IS_LOAD = "SET_MANAGER_PICTURE_IS_LOAD";
export const SET_PUBLICATIONS_IS_LOAD = "SET_PUBLICATIONS_IS_LOAD";
export const SET_ALBUM_IS_LOAD = "SET_ALBUM_IS_LOAD";

export const SET_FEEDBACKS_IS_NOT_LOAD = "SET_FEEDBACKS_IS_NOT_LOAD";
export const SET_FEEDBACKS_STATUS_IS_NOT_LOAD = "SET_FEEDBACKS_STATUS_IS_NOT_LOAD";
export const SET_EVENTS_IS_NOT_LOAD = "SET_EVENTS_IS_NOT_LOAD";
export const SET_MANAGER_PROFILE_IS_NOT_LOAD = "SET_MANAGER_PROFILE_IS_NOT_LOAD";
export const SET_CENTER_PROFILE_IS_NOT_LOAD = "SET_CENTER_PROFILE_IS_NOT_LOAD";
export const SET_CENTER_PICTURE_IS_NOT_LOAD = "SET_CENTER_PICTURE_IS_NOT_LOAD";
export const SET_MANAGER_PICTURE_IS_NOT_LOAD = "SET_MANAGER_PICTURE_IS_NOT_LOAD";
export const SET_PUBLICATIONS_IS_NOT_LOAD = "SET_PUBLICATIONS_IS_NOT_LOAD";
export const SET_ALBUM_IS_NOT_LOAD = "SET_ALBUM_IS_NOT_LOAD";