export const DISPLAY_ALERT = "SHOW_ALERT";
export const DISMISS_ALERT = "DISMISS_ALERT";

export const DISPLAY_MANAGER_PICTURE_MODAL = "DISPLAY_MANAGER_PICTURE_MODAL";
export const DISMISS_MANAGER_PICTURE_MODAL = "DISMISS_MANAGER_PICTURE_MODAL";

export const DISPLAY_CENTER_PICTURE_MODAL = "DISPLAY_CENTER_PICTURE_MODAL";
export const DISMISS_CENTER_PICTURE_MODAL = "DISMISS_CENTER_PICTURE_MODAL";

export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_PHONE = "SET_PHONE";
export const SET_EMAIL = "SET_EMAIL";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_NAME = "SET_NAME";
export const SET_DESCRIPTION = "SET_DESCRIPTION";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_ADDRESS_SECOND = "SET_ADDRESS_SECOND";
export const SET_ZIP_CODE = "SET_ZIP_CODE";
export const SET_CITY = "SET_CITY";
export const SET_CENTER_PHONE = "SET_CENTER_PHONE";
export const SET_REMEMBER = "SET_REMEMBER";

export const RESET_REGISTER_INFO = "RESET_REGISTER_INFO";
export const RESET_PROFILE_INFO = "RESET_PROFILE_INFO";

export const RESET_MANAGER_CENTER_INFO = "RESET_MANAGER_CENTER_INFO";

export const SET_MANAGER_KEEP_INFO = "SET_MANAGER_KEEP_INFO";
export const SET_CENTER_KEEP_INFO = "SET_CENTER_KEEP_INFO";

export const SET_MANAGER_INFO = "SET_MANAGER_INFO";
export const SET_CENTER_INFO = "SET_CENTER_INFO";

export const SET_MANAGER_PICTURE_PREVIEW = "SET_MANAGER_PICTURE_PREVIEW";
export const SET_CENTER_PICTURE_PREVIEW = "SET_CENTER_PICTURE_PREVIEW";

export const SET_MANAGER_PICTURE = "SET_MANAGER_PICTURE";
export const SET_CENTER_PICTURE = "SET_CENTER_PICTURE";

export const SET_PUBLICATIONS = "SET_PUBLICATIONS";
export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const SET_CURRENT_PUBLICATION = "SET_CURRENT_PUBLICATION";