const Fields = {
    EMAIL: "email",
    PASSWORD: "password",
    NEW_PASSWORD: "new_password",
    TOKEN: "token",
    FIRSTNAME: "first_name",
    LASTNAME: "last_name",
    PHONE: "phone_number",
    CENTER_PHONE: "center_phone_number",
    NAME: "name",
    DESCRIPTION: "description",
    ADDRESS: "address",
    ADDRESS_SECOND: "address_second",
    ZIP_CODE: "zip_code",
    CITY: "city",
    PICTURE: "picture",
    TITLE: "title",
    ALBUM: "album",
    PICTURE_ID: "picture_id",
    TEXT: "text",
    CREATION_DATE: "creation_date",
    PUBLICATIONS: "publications",
    PUBLICATION_ID: "publication_id",
    EVENT_ID: "event_id",
    START_DATE: "start_date",
    END_DATE: "end_date",
    DELETION_CAUSE: "deletion_cause",
    CUSTOM_PROGRAM_ID: "custom_program_id",
    NB_ACTIVITIES: "nb_activities",
    TOTAL_TIME: "total_time",
    AVAILABLE: "available",
    ACTIVITIES: "activities",
    CUSTOM_PROGRAMS: "custom_programs",
    NB_SUBSCRIBERS: "nb_subscribers"
};

export default Fields;